[project]
name = "smtperformance"
requires-python = ">=3.10"
version = "1.0"
dependencies = [
	"numpy==1.26.4",
    "pandas==2.2.2",
    "matplotlib==3.10.0",
    "scipy==1.13.1",
    "seaborn==0.13.2",
]